# asterisk 11.5.1 spec file
%define uname asterisk
%define gname asterisk

# XXX change buildroot
Summary: 				Asterisk PBX - light build for Futel
Name: 					asterisk
Version: 				11.5.1
Release: 				1
License: 				GPL
Group: 					Applications/Internet
URL: 						http://www.asterisk.org/
Source0: 				asterisk-11-current.tar.gz
Source1: 				asterisk.init
Source2: 				asterisk.logrotate
BuildArch: 			x86_64
BuildRoot: 			%{_tmppath}/%{name}-%{version}-%{release}-root
BuildRequires: 	openssl-devel, zlib-devel, perl, bison, speex-devel, doxygen
BuildRequires: 	newt-devel, ncurses-devel, glibc-kernheaders, sqlite-devel

%description
Asterisk is an Open Source PBX and telephony development platform that
can both replace a conventional PBX and act as a platform for developing
custom telephony applications for delivering dynamic content over a
telephone similarly to how one can deliver dynamic content through a
web browser using CGI and a web server.

Asterisk talks to a variety of telephony hardware including BRI, PRI,
POTS, and IP telephony clients using the Inter-Asterisk eXchange
protocol (e.g. gnophone or miniphone).

%package devel
Summary: Header files and development documentation for Asterisk
Group: Development/Libraries
Requires: %{name} = %{version}

%description devel
This package contains the header files needed to compile modules for Asterisk
as well as the developer documentation generated by doxygen.

# TODO:
# everything below here will need to be changed to accomodate out /opt
# preference. will note unchanged with a XXX

# XXX
%prep
%setup
# Replace /var/run by /var/run/asterisk since we don't run as root
%{__perl} -pi -e 's|/var/run$|%{_var}/run/asterisk|g' Makefile
# Fix lib vs. lib64 directory
%{__perl} -pi -e 's|/usr/lib/asterisk$|%{_libdir}/asterisk|g' Makefile
%{__perl} -pi -e 's|lib/libpri.so|%{_lib}/libpri.so|g' channels/Makefile

# XXX
%build
%{__make} PROC="%{_arch}" OPTIMIZE="%{optflags}"
%{__make} progdocs

# XXX
%install
%{__rm} -rf %{buildroot}

%{__make} install DESTDIR=%{buildroot}

# Install all sample config files
%{__make} samples DESTDIR=%{buildroot}

%{__install} -D -p -m 0755 %{SOURCE1} \
    %{buildroot}%{_sysconfdir}/rc.d/init.d/asterisk

%{__install} -D -p -m 0644 %{SOURCE2} \
    %{buildroot}%{_sysconfdir}/logrotate.d/asterisk

# We need that directory, see above
%{__mkdir_p} %{buildroot}%{_var}/run/asterisk

# Install demo sounds
for file in sounds/demo-*; do
    %{__install} -p -m 0644 $file %{buildroot}%{_var}/lib/asterisk/sounds/
done
for file in sounds/*.mp3; do
    %{__install} -p -m 0644 $file %{buildroot}%{_var}/lib/asterisk/mohmp3/
done


%clean
%{__rm} -rf %{buildroot}

%pre
# XXX not sure I need this at all.
# Add the "asterisk" user
/usr/sbin/useradd -c "Asterisk PBX" -G tty -s /sbin/nologin -r \
    -d "%{_var}/lib/asterisk" %{uname} 2>/dev/null || :

%post
/usr/sbin/chkconfig --add asterisk

%preun
if [ $1 -eq 0 ]; then
    /sbin/service asterisk stop >/dev/null 2>&1
    /sbin/chkconfig --del asterisk
fi

# XXX
# most of this likely will not change
# primarily replacing varwith opt here
%files
%defattr(-, root, root, 0755)
%doc BUGS ChangeLog configs/ CREDITS doc/*.txt HARDWARE LICENSE README SECURITY
%doc sounds.txt
%attr(750, %{uname}, %{gname}) %dir %{_sysconfdir}/asterisk
%attr(640, %{uname}, %{gname}) %config(noreplace) %{_sysconfdir}/asterisk/*.conf
%attr(640, %{uname}, %{gname}) %config(noreplace) %{_sysconfdir}/asterisk/*.adsi
%attr(640, %{uname}, %{gname}) %config(noreplace) %{_sysconfdir}/asterisk/*.ael
%config(noreplace) %{_sysconfdir}/logrotate.d/asterisk
%{_sysconfdir}/rc.d/init.d/asterisk
%{_libdir}/asterisk/
%{_sbindir}/*
%{_mandir}/man8/*.8*
%attr(-  , %{uname}, %{gname}) %{_var}/lib/asterisk/
%attr(750, %{uname}, %{gname}) %{_var}/run/asterisk/
%attr(750, %{uname}, %{gname}) %dir %{_var}/log/asterisk/
%attr(750, %{uname}, %{gname}) %dir %{_var}/log/asterisk/cdr-csv/
%attr(750, %{uname}, %{gname}) %dir %{_var}/log/asterisk/cdr-custom/
%attr(750, %{uname}, %{gname}) %dir %{_var}/spool/asterisk/
%attr(750, %{uname}, %{gname}) %dir %{_var}/spool/asterisk/voicemail/
%attr(750, %{uname}, %{gname}) %dir %{_var}/spool/asterisk/voicemail/default/
%attr(750, %{uname}, %{gname}) %dir %{_var}/spool/asterisk/voicemail/default/1234/
                                    %{_var}/spool/asterisk/voicemail/default/1234/*.gsm


# XXX
%files devel
%defattr(-, root, root, 0755)
%doc doc/api/html/*
%{_includedir}/asterisk/


%changelog
* Sat Dec 16 2017 Elijah St Clair <http://futel.net>
- Initial Spec build 11.5.1
